folder_tst: /home/user2/tst
folder_out: /home/user2/out
folder_ext: /home/user2/folder1
sub_folder: sub_folder
count: 3
bs: 1M
stat_file: /home/user2/stat.txt
key_t: -tzip
output_file: output.zip
host: 0.0.0.0
user: user2
password: '1111'
local_path: /home/user/test/p7zip.deb
remote_path: /home/user2/p7zip.deb